<?php
session_start();
$username=$_POST['username'];
$password=$_POST['password'];
$con=mysqli_connect('localhost','root');
mysqli_select_db($con,'jo_database_hum_banyange');
$q="select * from jis_table_ko_use_krna_hai  where username='$username' && password='$password'";
$result=mysqli_query($con,$q);
$num=mysqli_num_rows($result);
if($num==1)
{
$_SESSION['username']=$username;
header('location:http://localhost/dtask/main_page.php');
}
else
{
header('location:http://localhost/dtask/loginforproject.html'); 
}
?>